Info sources 27
CERTCC/SSVC pull request #101
Opened 2021-01-29 21:04 UTC by j---

fixes #27 
Because 27 is it's last part, closes #24

2021-02-01 20:43 UTC, cgyarbrough commented on doc/md_src_files/050_decision-points_1.md
One more aspect to consider, which builds on the previous sentence, is 'chain ability' of a given vulnerability. This is probably beyond the scope of this discussion, but certain vulnerabilities might be considered more 'beachhead' category (i.e., tending to allow for ingress to a system or software) and others are more effective at lateral movement or secondary instantiation in a blended or staged exploitation attempt. DoDCAR has done some initial work on the additive nature of exploits, but each of those is composed of underlying exploitable vulnerabilities.

2021-02-01 20:52 UTC, cgyarbrough commented on doc/md_src_files/055_decision-points_2.md
> +
Have we given any consideration to the relative value of vulnerabilities for even the non-obvious stages of the Kill Chain? Reconnaissance stage is an example. Some Vulnerabilities may not be valuable from an attack standpoint, but very valuable in allowing for asset enumeration and secondary exploit targeting. Has anyone ever analyzed the monetary amount of early stage vulnerabilities vs mid-to-later stage (post delivery) ones?

2021-02-01 20:54 UTC, j--- commented on doc/md_src_files/050_decision-points_1.md
I've captured this under #102. It's a good idea, but will take some additional work, I think.

2021-02-01 20:59 UTC, j--- commented on doc/md_src_files/055_decision-points_2.md
> +
I'm not familiar with anything specific. Bug bounty payouts (which we discuss as part of *value density*) give you some idea: https://zerodium.com/program.html . You can see the differential value between partial and complete-chain vuls in their value to zerodium. If you mean "value to the defender of closing a vul" in terms of most efficient improvement to defense posture, I think that is a question to capture for #78 .

2021-02-01 21:00 UTC, cgyarbrough commented on doc/md_src_files/050_decision-points_1.md
Agreed. I think that there is a difference is scope when looking at using SSVC to measure a single vulnerability vs. using chained vulnerabilities in an exploit attempt. Since SSVC is looking to replace CVSS for single vulnerabilities, I think the scope is appropriate. Future work.

2021-02-01 21:03 UTC, cgyarbrough commented on doc/md_src_files/050_decision-points_1.md
> +It means the analyst is not able to sketch a plausible path through all four kill chain steps.
I am sure we address this elsewhere in the discussion, but what are the four Kill Chain steps as we are defining them? Others will vary. Or are we just counting the post-delivery stages of the LM Kill Chain?

2021-02-01 21:04 UTC, cgyarbrough commented on doc/md_src_files/050_decision-points_1.md
> +[*Value Density*](#value-density) is described as *diffuse* or *concentrated* based on the resources that the adversary will gain control over with a single exploitation event:
Are we defining a 'single exploitation event' as utilizing a single vulnerability or will chained vulnerabilities be considered (i.e., blended attack)?

2021-02-01 21:08 UTC, j--- commented on doc/md_src_files/050_decision-points_1.md
> +It means the analyst is not able to sketch a plausible path through all four kill chain steps.
> steps 1-4 of the kill chain [@hutchins2011intelligence] for this vulnerability for some reason. These
    steps are reconnaissance, weaponization, delivery, and exploitation. 

Original definition, basically. First four (of 7) stages, so it is not post-delivery. Source: 
```
@article{hutchins2011intelligence,
  title={Intelligence-driven computer network defense informed by analysis of adversary campaigns and intrusion kill chains},
  author={Hutchins, Eric M and Cloppert, Michael J and Amin, Rohan M},
  journal={Leading Issues in Information Warfare \& Security Research},
  volume={1},
  pages={80},
  year={2011}
}
```
The last three stages, IIRC, are installation, command and control, and action on objectives.

2021-02-01 21:09 UTC, cgyarbrough commented on doc/md_src_files/055_decision-points_2.md
> +
Perhaps so. In reality though, bug bounties usually look for high value vulnerabilities which generally involve targeted software or systems. I think that vendors who pay bug bounties may not use the same logic as defenders of deployed systems when they allocate higher $$ to vulnerabilities payouts. Defenders usually value the 'beachhead' vulnerabilities which, if patched, disrupt the kill chain.

2021-02-01 21:10 UTC, j--- commented on doc/md_src_files/050_decision-points_1.md
> +[*Value Density*](#value-density) is described as *diffuse* or *concentrated* based on the resources that the adversary will gain control over with a single exploitation event:
I hadn't considered this question. But now that I'm prompted, I would say a blended attack counts as "one exploitation event". Does that cause any problems?

2021-02-01 21:13 UTC, j--- commented on doc/md_src_files/055_decision-points_2.md
> +
OK, then I think this is something to capture for #78 but in regard to across multiple vuls, what will be most efficient (e.g., fixing beachheads) rather than just within a single vul, what is the most efficient way to tackle it (which I think is what #78 focuses on now).

2021-02-01 21:17 UTC, cgyarbrough commented on doc/md_src_files/050_decision-points_1.md
> +[*Value Density*](#value-density) is described as *diffuse* or *concentrated* based on the resources that the adversary will gain control over with a single exploitation event:
It really depends on what you are trying to capture/measure. If effectiveness and morbidity of an exploitation event vs. the discrete value of a specific vulnerability is what you are wanting to measure then the exploit attempt would be appropriate. In reality severity of a vulnerability is linked to the exploit in which it is used. If you want to measure/capture the future damage a specific vulnerability (increased risk) then we might measure something very different--especially since a single vulnerability might be used in multiple exploitation events which may have very different outcomes.

2021-02-01 21:28 UTC, j--- commented on doc/md_src_files/050_decision-points_1.md
> +[*Value Density*](#value-density) is described as *diffuse* or *concentrated* based on the resources that the adversary will gain control over with a single exploitation event:
> have very different outcomes.

I know we're always dancing with this. Context matters. The same software can be used for very different purposes. But I think we've covered that where we say: 

> ## Reasoning Steps Forward
> 
> This aspect of scope is about immediacy, prevalence, and causal importance. Immediacy is about how soon after the decision point adverse effects should occur to be considered relevant. Prevalence is about how common adverse effects should be to be considered relevant. Causal importance is about how much an exploitation of the software in the cyber-physical system contributes to adverse effects to be considered relevant. Our recommendation is to walk a pragmatic middle path on all three aspects. Effects are not relevant if they are merely possible, too infrequent, far distant, or unchanged by the vulnerability. But effects are relevant long before they are absolutely certain, ubiquitous, or occurring presently. Overall, we summarize this aspect of scope as *consider credible effects based on known use cases of the software system as a part of cyber-physical systems*.

> It really depends on what you are trying to capture/measure.

Utility of the vul to the attacker in the context of the value density of instances of the vulnerable component =)

2021-02-04 14:34 UTC, ahouseholder requested changes
I had a few suggestions as inline comments in the changes. They're open for debate though so I'd be ok if they're given consideration and declined.

2021-02-04 14:34 UTC, ahouseholder commented on doc/md_src_files/050_decision-points_1.md
> +Gathering information for [active](#exploitation) is a bit harder.
I don't disagree with any of the points made here. 

Do you think it's worth saying anything about the idea that direct detection of exploitation is hard and that a lot of the "evidence of exploitation" comes from a path of incident -> malware -> re -> which vuls are involved, which really implies that the exploit has been found in deployed malware. I'm not close enough to 2020 era incident forensics to say more about the details there. But I suppose the main gist is that the path between incidents you know about and knowing which vul(s) is(were) involved is often quite lossy -- and that often the best you can do is rely on publicly available reporting.

2021-02-04 14:34 UTC, ahouseholder commented on doc/md_src_files/050_decision-points_1.md
> +Assessing [*Technical Impact*](#technical-impact) amounts to assessing the degree of control the vulnerability gives an attacker over the vulnerable component.
"the degree of control over the vulnerable component the attacker stands to gain by exploiting the vulnerability"

vulnerabilities are options to control. exploits exercise the option.

2021-02-04 14:34 UTC, ahouseholder commented on doc/md_src_files/050_decision-points_1.md
> +If an answer to one of the following questions is yes, then control is *total*:
if you accept the above comment's premise, then the bullets below might need to be prefixed with "after exploiting the vul, does the attacker gain..." or something similar. Point being to highlight the specific change in ability the attacker gains via exploitation (contrast with a possible reading that they have the ability with or without the vulnerability).

2021-02-04 14:34 UTC, ahouseholder commented on doc/md_src_files/050_decision-points_1.md
> +It means the analyst is not able to sketch a plausible path through all four kill chain steps.
Should we note that weaponization  might not be strictly necessary as a positive act? I.e., "wormable" vuls turn weaponization into a development process that happens once and then exploitation of vulnerable systems is reliable from that point on. A worm seems to automate recon, delivery, and exploitation, but I'm not sure that automation of the weaponization step was necessary. 

I may also be missing nuance in my understanding of how folks use the kill chain model.

2021-02-04 14:34 UTC, ahouseholder commented on doc/md_src_files/055_decision-points_2.md
> + - If [*Automatable*](#automatable) is [*yes*](#automatable), then choose [*controlled*](#system-exposure).
I'm not sure I see the logic here. How does automatable=yes lead to controlled vs small?

2021-02-04 15:47 UTC, j--- commented on doc/md_src_files/050_decision-points_1.md
> +It means the analyst is not able to sketch a plausible path through all four kill chain steps.
If something happens once and then can be copied repeatedly without human intervention, I think that falls under the usual definition of automation. I don't know what "positive act" means there. It was done at some point during the exploit development process. Is that not an act some how? If it can just be copied for each new target, then it's automated. Things like ASLR might interfere with automation here, but again overcoming something like ASLR can be automated. 

If you want to suggest additional text for Automation, can you open a new issue?

2021-02-04 15:55 UTC, j--- commented on doc/md_src_files/050_decision-points_1.md
> +Gathering information for [active](#exploitation) is a bit harder.
added to the end of the paragraph starting line 31.

2021-02-04 16:02 UTC, j--- commented on doc/md_src_files/050_decision-points_1.md
> +If an answer to one of the following questions is yes, then control is *total*:
Added prefix of question before all bullets, for better parallelism.

2021-02-04 16:04 UTC, j--- commented on doc/md_src_files/055_decision-points_2.md
> + - If [*Automatable*](#automatable) is [*yes*](#automatable), then choose [*controlled*](#system-exposure).
Because if automatable is *yes*, then reconnaissance is yes. And if the system can be automatically reconned, then I would say it's exposure is higher than small. 

Does that make sense? Do we need to write that in to the bullet?

2021-02-04 17:22 UTC, ahouseholder commented on doc/md_src_files/055_decision-points_2.md
> + - If [*Automatable*](#automatable) is [*yes*](#automatable), then choose [*controlled*](#system-exposure).
So I think you're saying that automatable is scoped to your environment vs. scoped to the vul? That is not what I expected. (I.e., "can be reconned _in your environment_" vs "can be reconned _in general, regardless whether you have mitigating configurations impeding that in your environment_")

2021-02-04 17:26 UTC, ahouseholder commented on doc/md_src_files/055_decision-points_2.md
> + - If [*Automatable*](#automatable) is [*yes*](#automatable), then choose [*controlled*](#system-exposure).
To answer your question directly though, I think whatever the reasoning is should be explicitly in the bullet.

2021-02-04 17:46 UTC, ahouseholder commented
commits in a7418370d2b8255aaa0d1f752f269452429ef8b3 look good to me

2021-02-04 18:13 UTC, j--- commented on doc/md_src_files/055_decision-points_2.md
> + - If [*Automatable*](#automatable) is [*yes*](#automatable), then choose [*controlled*](#system-exposure).
Automatable is about the usual deployment case. So it is not tied to the specific deployment environment. 
If you have suggestions for situations to "guard" this scenario, to state heuristics that can push users to *small*, please add them. I clarified these should be considered in order.

2021-02-04 18:41 UTC, j--- commented on doc/md_src_files/055_decision-points_2.md
> + - If [*Automatable*](#automatable) is [*yes*](#automatable), then choose [*controlled*](#system-exposure).
How's https://github.com/CERTCC/SSVC/pull/101/commits/64dae383cb22b98811003f83595efc22ccd8ed29 ?

2021-02-05 18:38 UTC, ahouseholder commented on doc/md_src_files/050_decision-points_1.md
> +It means the analyst is not able to sketch a plausible path through all four kill chain steps.
I think my confusion arises in that "weaponization" is a verb, but an exploit is an artifact. So automated exploitation can use the resulting artifact even if the production of the artifact (which I'm taking to be what "weaponization" means) itself was not automated.

The automation isn't necessarily doing anything to customize the exploit for the target, so it doesn't feel like weaponization is automated so much as it's just taken out of the process that needs to be automated. But yes, I acknowledge this concern is off-topic for _this_ PR.

2021-02-05 18:40 UTC, ahouseholder commented on doc/md_src_files/055_decision-points_2.md
> + - If [*Automatable*](#automatable) is [*yes*](#automatable), then choose [*controlled*](#system-exposure).
Yeah, that seems to capture it.

2021-02-05 18:42 UTC, ahouseholder approved these changes

2021-02-05 18:45 UTC, ahouseholder commented
I think all my concerns in this one are addressed. If @cgyarbrough confirms his approval this one should be ok to merge.

2021-02-05 20:07 UTC, cgyarbrough commented on doc/md_src_files/050_decision-points_1.md
> +It means the analyst is not able to sketch a plausible path through all four kill chain steps.
I approve this pull. Seems like for the discussions in scope that I'm good.

2021-02-05 20:07 UTC, cgyarbrough commented
I approve this pull.

2021-02-05 20:41 UTC, merged

2021-02-05 20:43 UTC, ahouseholder commented
squashed and merged.