initial draft of coordinator publication decision
CERTCC/SSVC pull request #103
Opened 2021-02-02 19:19 UTC by j---

Closes #11 
As long as #94 is also done.

2021-02-04 18:19 UTC, ahouseholder requested changes
No mods to the tree, just wording suggestions for the doc.

2021-02-04 18:19 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> +There are various ways an embargo period might be broken, including active exploitation of the vulnerability in the wild, but the decision described in this section assumes the embargo period is over
I'm a little put off by the phrasing around embargoes here. Mainly my concern is that breaking the embargo is a choice made to behave a certain way _after_ one or more indicator events have occurred. (timer expired, exploitation observed, public discussion, etc.) The indicator events themselves do not break the embargo automatically.

Suggested change:
As a matter of policy, CERT/CC will support an embargo information regarding the existence of a vulnerability
by through its choice not to publish information about the vulnerability while the a number of conditions hold:

1. A negotiated embargo timer has not expired. The default embargo period is [45 days](https://vuls.cert.org/confluence/display/Wiki/Vulnerability+Disclosure+Policy).
2. Other exceptions have not been met, including active exploitation of the vulnerability in the wild or other public discussion of the vulnerability details.

Regardless, the decision described in this section assumes the embargo period is over, one way or another.

2021-02-04 18:19 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> +While an issue that is tracked or declined may be reevaluated at a later date, unless that happens we would not publish about the vulnerability.
suggest replacing

> may be reevaluated at a later date,

with

> may be reevaluated at a later date leading to a change to coordinate status,

because the reevaluation may not change the status.

2021-02-04 18:19 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> + - Ampliative - amplifies and/or augments the existing public information about the vulnerability; "gets the word out."
suggest replace

> "gets the word out."

with

> for example: adds additional detail, addresses or corrects errors in other public information, draws further attention to the vulnerability, etc.

2021-02-04 18:35 UTC, j--- commented
@ahouseholder , does aaf85f3 address all your comments?

2021-02-05 17:38 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> +While an issue that is tracked or declined may be reevaluated at a later date, unless that happens we would not publish about the vulnerability.
resolved by aaf85f30db5c80b094e8dbd599a4b2ee614adff0

2021-02-05 17:39 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> + - Precedence - the publication would be the first publicly availablei, or co-occur with the first publicly available.
resolved by aaf85f30db5c80b094e8dbd599a4b2ee614adff0

2021-02-05 17:39 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> +As discussed in [Guidance on Communicating Results](#guidance-on-communicating-results), any SSVC decision may change over time as the inputs to that decision change.
resolved by aaf85f30db5c80b094e8dbd599a4b2ee614adff0

2021-02-05 17:39 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> +There are various ways an embargo period might be broken, including active exploitation of the vulnerability in the wild, but the decision described in this section assumes the embargo period is over
resolved by aaf85f30db5c80b094e8dbd599a4b2ee614adff0

2021-02-05 17:39 UTC, ahouseholder commented on doc/md_src_files/059_coordination-publish.md
> + - Ampliative - amplifies and/or augments the existing public information about the vulnerability; "gets the word out."
resolved by aaf85f30db5c80b094e8dbd599a4b2ee614adff0

2021-02-05 17:40 UTC, ahouseholder approved these changes

2021-02-17 19:40 UTC, laurie-tyz commented on doc/md_src_files/059_coordination-publish.md
> + - Precedence - the publication would be the first publicly availablei, or co-occur with the first publicly available.
s/availablei/available

2021-02-17 19:46 UTC, laurie-tyz commented on doc/md_src_files/059_coordination-publish.md
> +That is, [*Public Value Added*](#public-value-added) can only be downgraded through future iterations or re-evaluations.
If the coordinator initially believes the value is "Limited"; but then, the supplier doesn't publish or chooses not to mitigate or remediate the vulnerability, the coordinator may then decide that publication would be "Precedence". Starting again with "Limited"; if the supplier were to publish incorrect/misleading/unnecessarily vague information, the coordinator may then decide that publication would be "Ampliative".

2021-02-18 17:31 UTC, j--- commented on doc/md_src_files/059_coordination-publish.md
> +That is, [*Public Value Added*](#public-value-added) can only be downgraded through future iterations or re-evaluations.
The second one is a good point. Adjusting. 
I think the first one, the analyst never left "precedence." Analyst should stay in precedence until they have observable evidence that someone else has published first. I think that fits with the temporal aspect of the rest of SSVC -- the analysis is at a point in time about the state of the vul at that point in time. And since this decision is only being evaluated after an embargo has ended, there is no moral hazard in the question. For the second part of the first point, if a supplier pulls a fix that they had previously provided, I think that is handled under "supplier engagement" or "supplier cooperation," not here.

2021-02-18 19:48 UTC, ahouseholder commented
Just noticed this isn't explicitly stated in a comment yet: fixes #94

2021-02-19 15:09 UTC, j--- commented on doc/md_src_files/059_coordination-publish.md
> +Other organizations, such as [NVD](https://nvd.nist.gov/), would have different publication criteria and may want to include decision points or the decision itself from the [Coordination Triage Decis
Consider adding another / different example than NVD at some point.

2021-02-19 15:14 UTC, zmanion approved these changes
Discussed on Feb 19, minor edit, maybe look for publication example other than NVD, whose publication decision is essentially "if in CVE then publish."

2021-02-19 15:19 UTC, merged