Fix33 automation
CERTCC/SSVC pull request #114
Opened 2021-02-22 19:08 UTC by j---

closes #33

2021-02-24 18:52 UTC, ahouseholder requested changes

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/060_decision-trees.md
> +This situation is not new; an asset owner cannot prioritize which fixes to deploy to its assets if it does not know what assets it owns and their locations.
I think the "and their locations" is not actually true. I can prioritize fixes to cloud servers having no knowledge of their location, just the fact that they're my responsibility is sufficient, no?

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/060_decision-trees.md
> +Standards like the Software Bill of Materials (SBOM) [@manion2019sbom] would likely reduce the burden on asset management, and organizations should prefer systems which make such information availabl
"Emerging standards" -- I don't think SBOM is considered a standard yet (no standards body has issued a numbered doc about it, for example)

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/060_decision-trees.md
> +If an organization does not have an asset management or risk management (see Section 4.4.6.1) plan and process in place, then SSVC provides some guidance as to what information is important to vulner
Question (because I'm not sure how it works in this markdown-latex-pdf hybrid thing we're working on): Is this the right way to do internal cross-references? It seems pretty fragile to doc structure changes compared to some other way of doing it (e.g., label-based linking as one might do in LaTeX or HTML)

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +These include two aspects of [*Exploitation*](#exploitation), [*System Exposure*](#system-exposure), [*Technical Impact*](#technical-impact), and [*Public Safety Impact*](#public-safety-impact).
I realize this is saying "(2 of W), X, Y, and Z", but it is phrased in a way that made me trip over "2 of (W, X, Y, and Z)" as if I need to pick which two before I figured it out on a second reading.

I think you could just drop the "two aspects of" and the sentence remains true while it becomes more easily parsed.

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +However, if there is a viable information source we have not captured, please create an [issue on the SSVC GitHub page](https://github.com/CERTCC/SSVC/issues) explaining the information source and wh
Can we word this more carefully so it's more clear that we're asking for suggested categories of information sources, not specific feed products to subscribe to? I.e., we don't want this to turn into a solicitation for comments like "You left out Uncle Bob's Threat Feed which sources all the bad stuff from the darkest part of the dark web".

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +Although we are not aware of a comparative study of the different lists of active exploits, we expect they have similar properties to block lists of network touchpoints [@metcalf2015blocklist] and ma
Two sentences in a row start with "although"

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +Although the lists are all different, we expect they are all valid information sources to be used for this purpose.
Do we need to make this open-ended endorsement?

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +Namely, each list has a different view and vantage on the problem, which makes them appear to be different, but each list does a good job at accurately representing its particular vantage at a point
Do we need to keep saying they're "valid" or "good" as opposed to "we're not endorsing any particular feed, but we acknowledge they exist, and folks should consider using them as part of their information gathering" or something like that. I'd rather not commit to much more than: these things exist and are could be useful for this purpose.

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +[*System Exposure*](#system-exposure) should be informed by the various scanning platforms such as and Shodan and Shadowserver.
"can" instead of "should"?

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +There are some information sources that are not exactly suited to make SSVC decisions, but with a bit of work could be used directly.
If they can be "used directly with a bit of work" then they are "suited" for it. I think "were not designed with SSVC in mind, but can be adapted to work" is the idea you're getting at here.

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +If the value of Scope is Changed in CVSSv3, then the impact metrics are the maximum of the impact on the vulnerable component and other components in the environment.
Is there a way to rephrase this to make it more clear that you mean Scope="Changed" and not that there is a pending change to CVSSv3? The capital C in Changed reads as a typo. Quotes, italics, font, something to offset it as a literal value rather than a word in the sentence.

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +As long as the impact metrics in CVSS are clearly about just the vulnerable component, if confidentiality, integrity, and availability metrics are all "high" then [*Technical Impact*](#technical-impa
Move the "as long as" clause to the end of the sentence? That's a lot to hold in memory until you know what to apply it to.

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +For some classes of vulnerabilities, the proof of concept on how to exploit them is well known and already part of open-source tools.
Maybe "the method of exploitation" instead of "the proof of concept on how to exploit them"? It seems awkward as written.

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +Such a check could not be exhaustive, since there are other conditions that satisfy [*proof of concept*](#exploitation), but if paired with automatic searches for exploit code in public repositories,
Break this into two sentences at "but"?

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +Creatinga mapping between CPE and [*Public Safety Impact*](#public-safety-impact) could be a community effort to associate a value with each CPE entry, or an organization might label a fragment of th
space between "Creating a"

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +While that is broad analysis frame, it means that any community that shares a similar set of adversaries and a similar region of the Internet can share the same response to both decision points.
that is _a_ broad analysis frame

2021-02-24 18:52 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +These factors suggest there would be a viable market for an information feed about these decision points.
s/would/could/

2021-02-25 14:46 UTC, j--- commented on doc/md_src_files/060_decision-trees.md
> +This situation is not new; an asset owner cannot prioritize which fixes to deploy to its assets if it does not know what assets it owns and their locations.
Is calling a virtual address or identifier a location too much of a stretch for "location"?

2021-02-25 14:48 UTC, j--- commented on doc/md_src_files/060_decision-trees.md
> +Standards like the Software Bill of Materials (SBOM) [@manion2019sbom] would likely reduce the burden on asset management, and organizations should prefer systems which make such information availabl
ack

2021-02-25 14:49 UTC, j--- commented on doc/md_src_files/060_decision-trees.md
> +If an organization does not have an asset management or risk management (see Section 4.4.6.1) plan and process in place, then SSVC provides some guidance as to what information is important to vulner
No, it's left over from the MS-word to Markdown conversion. 
We can open a new issue to get all those.
This just looks like new text b/c I broke up the lines. I didn't actually add it now.

2021-02-25 14:57 UTC, j--- commented on doc/md_src_files/082_relatedSystems.md
> +Although the lists are all different, we expect they are all valid information sources to be used for this purpose.
"valid" is a fairiy low bar. And the blacklist research suggests this is true. The lists are all valid for some segment of the internet, it's just probably not your segment. I'll add in that "fit to your env" bit.

2021-02-25 15:05 UTC, j--- commented on doc/md_src_files/082_relatedSystems.md
> +Namely, each list has a different view and vantage on the problem, which makes them appear to be different, but each list does a good job at accurately representing its particular vantage at a point
I mean, I think the 8 years of research on blocklists supports the sentence, though there is a bit of redundancy in there I've trimmed out.

2021-02-25 15:15 UTC, j--- commented on doc/md_src_files/082_relatedSystems.md
> +If the value of Scope is Changed in CVSSv3, then the impact metrics are the maximum of the impact on the vulnerable component and other components in the environment.
ack

2021-02-25 15:18 UTC, j--- commented on doc/md_src_files/082_relatedSystems.md
> +For some classes of vulnerabilities, the proof of concept on how to exploit them is well known and already part of open-source tools.
how's this?

2021-02-25 15:19 UTC, j--- commented on doc/md_src_files/082_relatedSystems.md
> +Such a check could not be exhaustive, since there are other conditions that satisfy [*proof of concept*](#exploitation), but if paired with automatic searches for exploit code in public repositories,
ack

2021-02-25 15:21 UTC, j--- commented on doc/md_src_files/082_relatedSystems.md
> +These factors suggest there would be a viable market for an information feed about these decision points.
I think that changes the meaning too much, consider the pushed change?

2021-02-25 15:58 UTC, ahouseholder commented on doc/md_src_files/060_decision-trees.md
> +This situation is not new; an asset owner cannot prioritize which fixes to deploy to its assets if it does not know what assets it owns and their locations.
Identity is not location. If what is meant is identity, then it should say that.

The enumeration of what assets are deployed and which assets have vulnerable components is I think the thing we're getting at here. And that's a mapping of (asset-id has vul-id), or more likely it's mediated through (asset-id has component-id has vul-id).

Yes, location can be a kind of identity (e.g., IP address X has component version Y with vul Z is an adequate way of applying asset management to this problem). It's just not the only kind.

2021-02-25 16:06 UTC, j--- commented on doc/md_src_files/060_decision-trees.md
> +This situation is not new; an asset owner cannot prioritize which fixes to deploy to its assets if it does not know what assets it owns and their locations.
How's https://github.com/CERTCC/SSVC/pull/114/commits/bc244f9d96aa31a80780a3cd21adb6f6e1778dc1 ?

2021-02-25 16:25 UTC, ahouseholder commented on doc/md_src_files/060_decision-trees.md
> +This situation is not new; an asset owner cannot prioritize which fixes to deploy to its assets if it does not know what assets it owns and their locations.
Yeah that works.

2021-02-25 16:26 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +For some classes of vulnerabilities, the proof of concept on how to exploit them is well known and already part of open-source tools.
Not sure what "this" is referring to...?

2021-02-25 16:31 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +These factors suggest there would be a viable market for an information feed about these decision points.
Yeah, I was mainly concerned about asserting the probable future existence of a viable market versus the plausibility of such a market.

2021-02-25 16:32 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +For some classes of vulnerabilities, the proof of concept on how to exploit them is well known and already part of open-source tools.
assuming you meant 51559c0ecfa7cd5f9d701e6a98a0c20a7bb5fc05, yes, that covers it

2021-02-25 16:32 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +However, if there is a viable information source we have not captured, please create an [issue on the SSVC GitHub page](https://github.com/CERTCC/SSVC/issues) explaining the information source and wh
This seems to be fixed in 51559c0ecfa7cd5f9d701e6a98a0c20a7bb5fc05

2021-02-25 16:33 UTC, ahouseholder approved these changes
current revisions look good

2021-02-25 16:33 UTC, merged

2021-02-25 16:38 UTC, ahouseholder commented on doc/md_src_files/082_relatedSystems.md
> +Although the lists are all different, we expect they are all valid information sources to be used for this purpose.
The set of lists you studied is a subset of "all the lists". I'm not arguing that valid sources exist. Just that it's an overly broad assertion that they are "all valid information sources".