Feature/add cvss decision points py
CERTCC/SSVC pull request #343
Opened 2023-10-16 16:25 UTC by ahouseholder

Depends on
- #340 
- #342 

Adds Decision Point and Decision Point Group models for CVSS v1, v2, and v3 vectors.

Includes unit tests to validate output against json schema from #340.

- Resolves #330

2023-10-16 16:32 UTC, ahouseholder commented
Note: everything new in this PR that is not already in #342 is in commit 8f2bc07

2023-10-27 15:01 UTC, j--- requested changes
I'm flagging some things here but the general question is about how we are applying SSVC decision point versioning. 

If we accept any CVSS metric name change as a new object, we are essentially assuming that CVSS only changes names when the major/minor/patch version rules introduced in #350 don't apply. I do not believe that's the case, I think CVSS has changed metric names for messaging reasons. These are valid reasons, but they differ from our agreed SSVC decision point versioning rules. If we are properly integrating CVSS metrics as SSVC decision points, I suggest we apply our own versioning rules (which I think means we do not treat a metric name change as automatically a new object).

2023-10-31 18:26 UTC, ahouseholder commented on src/ssvc/decision_points/cvss/attack_complexity.py
Updated in [e3cd036](https://github.com/CERTCC/SSVC/pull/343/commits/e3cd0362343bd71cdf6f9fbcf1be48e5fc5a566f)

2023-10-31 18:27 UTC, ahouseholder commented on src/ssvc/decision_points/cvss/access_vector.py
Updated in https://github.com/CERTCC/SSVC/pull/343/commits/d54862a6d4c6654b91213ccf28833370c547d4e8

2023-10-31 19:02 UTC, ahouseholder commented on src/ssvc/decision_points/cvss/access_complexity.py
The shortcoming of ADR 0003 is that we address versioning changes mostly in terms of changes to the underlying decision point values. We neglected to address changes to the decision point descriptors (name, key, description) itself.

2023-11-07 16:31 UTC, j--- approved these changes

2023-11-07 17:33 UTC, merged