Tool to auto populate documentation examples for decision point objects
CERTCC/SSVC pull request #370
Opened 2023-11-02 17:18 UTC by ahouseholder

This PR adds `doctools.py`, which does the following:

- Loads existing SSVC decision points
- For each version of each decision point:
   - Emit the decision point as a `json` file
   - Emit a markdown blob that can be used as an include in the documentation
   - Create a soft link to the decision point name for the most recent version thereof (to make it easier to generate updates)

Also included:

- The content generated by the above
- Edits to the decision point markdown files to include the generated content
- A relatively unrelated change to reorganize the `ssvc.dp_groups` module for future maintenance convenience.

This PR is the final chunk of what was in PR #339. Note that when you look at the file-level changes, it appears as if a lot has changed. However, I attempted to break up those changes in the commits as follows:

- 4d5a4a4a27e349d424f89d2cd365cb82b460ec35 reorganizes `ssvc.dp_groups`
- 90c736b81c3e6d9fd9a24a042a73d1efc323a2d5 is the `doctools.py` script all by itself
- 2aa8c39d39f3b6eda2974ff0e56528b85df2a7a0 has the content that `doctools.py` emits
- 2c7bd87689af7dd2fb494be3291d6c5b8d3be82b adds a few decision points that we had previously not included in the reference section (virulence, utility, human impact, public safety impact). The accompanying docs include links between the various constituent elements for the compound ones. The page for _virulence_ notes that it is superseded by _automatable_.
- 3809a838c125bc1f87f8925cff3cdd95901968b7 modifies existing docs to include the generated content. Note that for decision points having multiple extant versions, there is now a _previous version_ section at the bottom of the page so folks can see what the older versions looked like
 
- resolves #364

2023-11-08 19:39 UTC, j--- requested changes
There are a couple implications in here that I'd like to discuss before approving. The only one that I'd consider as truly blocking is the naming of Virulence as a 1.0 metric. By blocking, I mean I want to resolve that discussion before we commit this PR. Not sure which way it will be resolved.

docs/_generated/decision_points/safety_impact_1_0_0.md looks less good than the original PDF, because the table there was structured very differently than the other decision points. It has these sub-categories of physical harm, psychological harm, etc. And I think these are, predictably, printing in a way that is confusing.

I propose we make a new issue to attempt a re-write of the safety impact decision point to make the text more amenable to being consistent with our more automated design and document management process. The code here does what is expected given the text for safety impact. So it's not a problem with this PR. 

I think the question about whether compound decision points are named and stored differently to keep them separate can also be a new issue that we can discuss separately and modify things later if we decide to do that.

2023-11-09 15:44 UTC, ahouseholder commented on data/json/decision_points/virulence_1_0_0.json
I think there are a few things going on here:
1. Virulence was used in a "named version" of SSVC. We thought it was good enough _at the time_. That to me argues that Virulence should be at 1.0.0. It's only in retrospect that we know it wasn't quite what we needed.
2. It's both reasonable and accurate to say that Automatable evolved from Virulence. However, since the name, key, description, and all values changed it's hard for me to see how Automatable is not a new thing. Virulence -> Automation seems like a new (related, but still sufficiently novel) concept refinement that makes it a different thing. Hence I'm arguing for version discontinuity.
3. Even if we made Virulence version N of the thing that Automatable became version N+1 of, that still doesn't take Virulence out of service. We don't currently have a mechanism to designate decision point deprecation. This was raised in https://github.com/CERTCC/SSVC/blob/main/docs/adr/0006-ssvc-decision-point-versioning-rules.md where we said:

> We think that Decision Points SHOULD have a way to indicate a deprecated status as a means to stave off future regrets. This implies the need for a way to denote the status of a decision point in addition to its version. Decision Point status will need to be addressed in a separate decision (or decisions) regarding decision point lifecycles.

We can capture item 3 in a new issue.

2023-11-09 15:47 UTC, ahouseholder commented on docs/_generated/decision_points/safety_impact_1_0_0.md
Captured this comment in 

- #380

2023-11-09 16:04 UTC, ahouseholder commented on data/json/decision_points/utility_1_0_1.json
> +      "description": "No to automatable and diffuse value"
I think the text came from the 2.1 PDF:

<img width="742" alt="Screenshot 2023-11-09 at 11 01 37 AM" src="https://github.com/CERTCC/SSVC/assets/2594236/8d9f5ccc-0bdb-42ba-9a1c-ed8b939279d1">

2023-11-09 16:06 UTC, ahouseholder commented on docs/reference/decision_points/virulence.md
Resolving this comment as it's consolidated into the thread at https://github.com/CERTCC/SSVC/pull/370#discussion_r1387099436

2023-11-09 16:16 UTC, ahouseholder commented on mkdocs.yml
In text explanations, I agree that we should note that they're a bit different. And that we should allow for either explicit or implicit chaining of decision points (e.g., where policy A's outcome group is used as a decision point in policy B). This extends into the "outcomes are just a flavor of decision points" conversation I brought up elsewhere.

But in terms of expressing the decision points themselves, I don't think they're materially different enough to change the way we collect them in the file system.

My counterproposal then is that the text content on the individual pages for the compound decision points should make it clear that they're provided as a notational convenience and expected to be used with specific semantics (i.e., a hard-coded policy) when they do appear.

2023-11-09 16:19 UTC, ahouseholder commented on data/json/decision_points/utility_1_0_1.json
> +      "description": "No to automatable and diffuse value"
And to amend the terse reply above, yeah, I agree they should use proper names for other decision point dependencies.

2023-11-09 19:49 UTC, j--- commented on data/json/decision_points/utility_1_0_1.json
> +      "description": "No to automatable and diffuse value"
Ah, so it was also wrong in the original. So not an error in introduced by this PR. But still something we should address.

2023-11-09 20:19 UTC, j--- commented on mkdocs.yml
Making that clear in the text descriptions is enough for me.

2023-11-09 20:22 UTC, j--- commented on mkdocs.yml
#382 created, closing this thread.

2023-11-09 20:24 UTC, j--- commented on data/json/decision_points/utility_1_0_1.json
> +      "description": "No to automatable and diffuse value"
Can address in #383 , don't need to address here.

2023-11-09 20:44 UTC, j--- commented on data/json/decision_points/virulence_1_0_0.json
I think "support" to me includes at least an implication that we would recommend some stakeholder ever use the decision point. So slightly more than just "would not delete". I think it's OK to call things that we changed 3 to 4 years ago as v0.* at that time. I also am trying to think about this from a novice's point of view and what they see when they try to get in to using SSVC. Reducing options that they have to sift through is would provide value to that end. And if our goal is to be accessible and usable, then we can at least consider that value. 

I don't think that there is a particular reason that a decision point group (like SSVC v1.0) has to only include decision points that are v1.0.0 or higher? At least, that's not included in docs/adr/0005-ssvc-decision-point-group-versioning.md. So I'm not convinced that Virulence being in SSVC v1 makes it a v1 decision point. It was certainly good enough for publication in v1, but that just represents our first attempt at everything (documentation, process, rationale, decision points, decision point groups, trees, etc.). We could have v0.* elements in there. 

On the other hand, I see good value in linking the description of automatable to the term virulence. Virulence is in some ways more evocative. In the CVSS v4 discussions about automatable, "wormable" was a useful evocative metaphor as well. To some extent, I think linking them as v0* of Automatable makes virulence easier to find as an antecedant and metaphor for automatable. 

Also, the concept has changed very little, it's just a rebranding really. 
The text of Virulence in the v1 whitepaper is
> Slow. Steps 1-4 of the kill chain cannot be reliably automated for this vulnerability for some reason. These steps are reconnaissance, weaponization, delivery, and exploitation. Example reasons for why a step may not be reliably automatable include (1) the vulnerable component is not searchable or enumerable on the network, (2) weaponization may require human direction for each target, (3) delivery may require channels that widely deployed network security configura-tions block, and (3) exploitation may be frustrated by adequate exploit-prevention techniques enabled by default; ASLR is an example of an exploit-prevention tool.

This is basically identical to what's in docs/reference/decision_points/automatable.md now, just the current file is reorganized to take the examples out into a separate enumerated list. 

And the inclusion of "not reliably automatable" is not a mistake in the v1 description text. "Not reliably virulent" didn't sound right, so we have been using "automatable" to describe this decision point from the beginning.

2023-11-13 20:41 UTC, ahouseholder commented on data/json/decision_points/virulence_1_0_0.json
I ported in the version diff checker from #377, and put Virulence 1.0.0 and Automatable 2.0.0 (f.k.a. Automatable 1.0.0) through the diff:

```shell
(minor) Automatable name changed from Virulence
(patch) Automatable v2.0.0 description changed
(major) Automatable v2.0.0 key changed
Automatable v2.0.0 version changed from 1.0.0
(major) Automatable v2.0.0 removes value Slow
(major) Automatable v2.0.0 removes value Rapid
(major or minor) Automatable v2.0.0 adds value Yes
(major or minor) Automatable v2.0.0 adds value No
Automatable v2.0.0 appears to be a major change
(maybe_new_obj) Automatable v2.0.0 changed name, description, and key. Potentially new object depending on context.
```

I'm personally still not sold on retconning Virulence to v0.2.0. I think our intent with SSVC v1.0 was that everything in it was v1.0.0, and if we had meant otherwise we could have said so at the time. The versioning sequence (and the fact that Virulence now appears at the bottom of the Automatable page as a "previous version" with a warning that it was superseded by Automatable is sufficent to wave off future SSVC novices from attempting to use it.

If we need to get broader input on this, I suggest that we refocus the decision in this PR to "does this tool do what we want it to do at present?" -- namely does it generate content in the right place given what's in the code. I think, as noted in other comments, that _content_  issues are a distinct from whether this code does what it says. Now that Virulence and. Automatable belong to the same version continuity, I think the specific version numbers become at most a content problem to be treated in a separate issue / discussion thread rather than a blocker for this PR.

2023-11-13 20:54 UTC, ahouseholder commented on data/json/decision_points/virulence_1_0_0.json
Note that the generated json and md files still reflect `virulence` as separate files for inclusion purposes, because they use the decision point name and version to automatically determine what file to drop the content into. However, `docs/reference/decision_points/automatable.md` is the only place in a linked page that incorporates them.

2023-11-14 16:05 UTC, j--- commented on data/json/decision_points/virulence_1_0_0.json
Thanks. v1 and v2 are fine with me, and we can make another issue if we decide we need to sort out version number details, as you suggest. Thanks!

2023-11-14 19:26 UTC, merged