Update coordination decision, prepare docs
CERTCC/SSVC pull request #405
Opened 2024-01-29 20:38 UTC by laurie-tyz

- resolves #372
- resolves #373

2024-01-30 18:06 UTC, ahouseholder requested changes

2024-01-30 18:06 UTC, ahouseholder commented on docs/howto/coordination_decisions.md
> +[Report Public]_'/coordinator_trees.md/reference/decision_points/report_public/'
for example: from `docs/howto/coordination_decisions.md`, `../reference/decision_points/report_public/report_public.md`

Note relative link and explicitly the index.md

2024-01-30 18:34 UTC, ahouseholder commented on docs/howto/coordination_decisions.md
> +[Report Public]_'/coordinator_trees.md/reference/decision_points/report_public/'
Also, this list should be moved to replace the TODO item on line 17. It doesn't belong at the end of the file.

2024-02-05 22:04 UTC, sei-vsarvepalli approved these changes

2024-02-13 18:44 UTC, closed without merging

2024-02-13 20:21 UTC, laurie-tyz commented
My numbers are all wrong.  Look for #392 instead of #372 and #393 instead of #373.

Can I undo my pull requests and renumber them?