Revise compound decision points documentation
CERTCC/SSVC pull request #428
Opened 2024-02-01 21:45 UTC by ahouseholder

- resolves #375 
- resolves #383 

We had compound decision points showing up in both the Topics and Reference section. This consolidates all that into the Reference section.

It also updates the text of the python objects and generated JSON to more accurately reflect the proper decision point names.

2024-02-02 20:44 UTC, j--- requested changes
Minor questions about lines in docs/reference/decision_points/utility.md. Once those are answered, can merge, everything else looks good.

2024-02-02 20:44 UTC, j--- commented on docs/reference/decision_points/utility.md
> +*Utility* estimates an adversary's benefit compared to their effort based on the assumption that they can exploit the vulnerability.
Is this intentionally a repetition of line 13?

2024-02-02 20:44 UTC, j--- commented on docs/reference/decision_points/utility.md
> +*Utility* is independent from the state of [*Exploitation*](exploitation.md), which measures whether a set of adversaries have ready access to exploit code or are in fact exploiting the vulnerability
Is this intentionally a repetition of line 14?

2024-02-02 21:20 UTC, ahouseholder commented on docs/reference/decision_points/utility.md
> +*Utility* estimates an adversary's benefit compared to their effort based on the assumption that they can exploit the vulnerability.
Oof. Bad file merge on my side. I'll fix this and the next one in an update to the branch next week.

2024-02-02 21:20 UTC, ahouseholder commented on docs/reference/decision_points/utility.md
> +*Utility* is independent from the state of [*Exploitation*](exploitation.md), which measures whether a set of adversaries have ready access to exploit code or are in fact exploiting the vulnerability
See previous comment https://github.com/CERTCC/SSVC/pull/428#discussion_r1476743127 above

2024-02-05 15:29 UTC, ahouseholder commented on docs/reference/decision_points/utility.md
> +*Utility* is independent from the state of [*Exploitation*](exploitation.md), which measures whether a set of adversaries have ready access to exploit code or are in fact exploiting the vulnerability
fixed in 785f928

2024-02-05 15:30 UTC, ahouseholder commented on docs/reference/decision_points/utility.md
> +*Utility* estimates an adversary's benefit compared to their effort based on the assumption that they can exploit the vulnerability.
Fixed in 785f928

2024-02-05 17:55 UTC, j--- approved these changes

2024-02-05 19:55 UTC, merged