add paragraph about risk tolerance
CERTCC/SSVC pull request #43
Opened 2020-10-08 19:05 UTC by ahouseholder

fix #20

2020-10-08 20:30 UTC, j--- requested changes
This is good.
Is there any citation or other document that discusses the different categories of risks that need to be balanced in infosec? 
OCTAVE does not have the level of categorization I'm hoping for. 

Do we have a definition of "risk" that we agree with? 
I'd like to avoid the simple (impact x likelihood) formulation of risk, not that it's wrong per se, but because it leaves out distribution of harms, correlated risks, and the uncertainty distribution on the likelihood. 

Should both of these be new issues, or are they necessary for closing this one?

2020-10-13 14:29 UTC, ahouseholder commented
I think the risk definition question is a separate issue. See #49 

Categories of risk: I'm not familiar with any canonical lists, but can take a look.

2020-10-13 14:42 UTC, ahouseholder commented
This might be relevant:
Cebula, James., & Young, Lisa. 2010. A Taxonomy of Operational Cyber Security Risks (Technical Report CMU/SEI-2010-TN-028). Pittsburgh: Software Engineering Institute, Carnegie Mellon University. http://resources.sei.cmu.edu/library/asset-view.cfm?AssetID=9395

It seems to me that "Change risk" is a combination of subclass 2.2 ("systems and technology failures:software") and class 3 ("Failed internal processes") -- there is risk arising from making a change to an operational context that might not be able to absorb it well.

Whereas "Vulnerability risk" is a type of 1.2 ("actions of people:deliberate") -- the risk arises from an attacker intentionally causing harm.

If that makes sense I can modify the added text to refer to those.

2020-10-16 12:31 UTC, j--- commented
I think the paper by Jim and Lisa is good. I would suggest that "change risk" includes all of 2 and 3, not just 2.2 and 3. The change might overload some hardware (2.1) or cause an integration failure (2.3.3), for example. But overall, I like it, and the document links to other standards as well, so people can map to their standard if there is one they must comply with. So I'm in favor of adding that in. 

We should make sure that we don't lose sight of cost of doing the work, but that's #35 and can be handled there. We might want to leave some breadcrumbs to make sure we cross reference these two discussions with each other in the document, is all.

2020-10-21 16:56 UTC, ahouseholder commented
Ok, added para on line 73 of diff to refer to the Risk Taxonomy paper. Citation added to .bib file too.

2020-10-21 17:40 UTC, j--- approved these changes
Thanks! Looks good to me.

2020-10-21 17:40 UTC, merged