Update Exploitation:PoC definition
CERTCC/SSVC pull request #442
Opened 2024-02-07 20:40 UTC by ccullen-cert

I changed the content to the following:

description="A POC can be accessed either on the clear web or in illicit locations, regardless of a paywall"
    " or the vulnerability has a well-known method of exploitation.",
    
I believe this covers the intended goal behind this decision point. There are an infinite amount of variations and combinations for PoC to be accessed by a TA, and paywalls won't stop a TA from gaining access to them. The point, from my understanding, is that this decision point is used to signify an incoming likelihood of exploitation by a threat actor. If the PoC can be accessed, even determined lower level TAs can acquire it from behind a paywall, even if it is provided by a legitimate enterprise.  
There are other nuances to the decision point, but that was what guided by decision in changing this up. 

The second point: "or the vulnerability has a well-known method of exploitation" covers an instance where a PoC may not have an explicit PoC or otherwise formal place where individuals can acquire a PoC, but the vulnerability can be exploited through already known methods that do not require much effort to accomplish or put together.

2024-02-07 20:49 UTC, j--- requested changes
In addition to text comments, I think that https://github.com/CERTCC/SSVC/blob/main/src/ssvc/decision_points/exploitation.py is the canonical place that the text needs to be updated, so after we agree on text let's make sure it's reflected there also before PR is finalized. 
Thanks!

2024-02-07 20:49 UTC, j--- commented on src/ssvc/decision_points/exploitation.py
> +    description="A POC can be accessed either on the clear web or in illicit locations, regardless of a paywall"
Can we make this consistent with the CISA description rather than trying to spin something new?  Per #353 
CISA's SSVC version of State of Exploitation removes them https://www.cisa.gov/sites/default/files/publications/cisa-ssvc-guide%20508c.pdf

Also, well-known methods of exploitation have been ground out a bit in #376, so we could productively reference that in the documentation.

2024-02-07 21:54 UTC, ahouseholder commented
If the wording changes in the python, then we may also need to bump a version number. I'll have to take a look at that after the other changes settle out but before we merge this one.

2024-02-07 21:56 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
> +    description="A POC can be accessed either on the clear web or in illicit locations, regardless of a paywall"
re: #376, it's already part of the Exploitation doc page. 

See https://certcc.github.io/SSVC-staging/reference/decision_points/exploitation/

2024-02-07 21:58 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
>  POC = SsvcDecisionPointValue(
This should probably get a new `POC_2` name and a new version of the decision point rolled in.

2024-02-08 17:30 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
> +    description="A POC can be accessed either on the clear web or in illicit locations, regardless of a paywall"
So taking the words from the CISA doc, edited to stay consistent with [ADR-0007 Object Descriptions Exclude Examples
](https://github.com/CERTCC/SSVC/blob/main/docs/adr/0007-descriptions-exclude-examples.md), it seems like we might want to use the following text:

| Value | Description |
| --- | --- |
| None | There is no evidence of active exploitation and no public proof of concept (PoC) of how to exploit the vulnerability. |
| Public PoC | One of the following is true: (1) Typical public PoC exists in sources such as Metasploit or websites like ExploitDB; or (2) the vulnerability has a well-known method of exploitation.
| Active | Shared, observable, and reliable evidence that cyber threat actors have used the exploit in the wild; the public reporting is from a credible source. |

2024-02-08 21:22 UTC, j--- commented on src/ssvc/decision_points/exploitation.py
>  POC = SsvcDecisionPointValue(
I think the version number needs to change here, right? 
https://github.com/CERTCC/SSVC/blob/524ad63e76dec34f1bed25a93a862e45feac317b/src/ssvc/decision_points/exploitation.py#L39

And what a new version means is that `exploitation` uses `POC` instead of something else. So if you leave this one as `POC`, then the legacy version of `POC` needs a new name so that `exploitation` version 1.1.0 can be distinguished from version 1.0.0 (current version). 

I think it'll be 1.1.0, at least.

2024-02-08 21:23 UTC, j--- commented on src/ssvc/decision_points/exploitation.py
> +    description="A POC can be accessed either on the clear web or in illicit locations, regardless of a paywall"
Thanks!

2024-02-09 18:45 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
>  POC = SsvcDecisionPointValue(
yes, it needs to be a new version. I just

- restored the original POC definition in ad99a1d 
- re-added the new one as POC_2 in 5604ee6
- updated copyright/docstring (my local tooling does this automatically) in 99b7125
- regenerated examples from the new version in 9a890aa

I'm going to mark this conversation resolved and re-request review on it.

2024-02-09 18:47 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
> +    name="PoC",
I reversed these changes. Because we're versioning decision points, we can't modify older ones in place, we need to append new ones. That gets fixed in the next commit.

2024-02-09 18:53 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
> +)
This is how to modify an existing decision point value: copy it to a new variable name, then create a new decision point (below) that uses it. Modifying existing decision point values can't happen or else we lose versioning.

2024-02-09 18:53 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
>          ACTIVE,
Here I added a new version of the Exploitation decision point that picks up the new POC_2 value.

Just noticing I should have named it EXPLOITATION_1_1_0. I'll fix that in another commit.

2024-02-09 18:53 UTC, ahouseholder commented on src/ssvc/decision_points/exploitation.py
> +    print_versions_and_diffs(versions)
When you run this module as a standalone, it'll suggest whether it's a major, minor, or patch version change based on the delta. It suggested major version because the name changed from PoC to Public PoC, but I overrode that and made it a minor version change since the two values are semantically compatible.

2024-02-09 19:39 UTC, ahouseholder commented
Based on this PR, I also created the following how-to in the SSVC wiki for future reference:

https://github.com/CERTCC/SSVC/wiki/Modifying-Decision-Point-Values

Thanks especially to @ccullen-cert for being an unwitting guinea pig being the first person other than me to attempt modifying a decision point definition in the python files, so it wasn't until now that I realized how much wasn't obvious about the versioning process. Hence the doc linked above. Hopefully that makes it easier the next time through.

2024-02-09 19:52 UTC, ahouseholder approved these changes
I'm good to go with this as it currently stands.

2024-02-09 20:13 UTC, sei-vsarvepalli approved these changes
All looks clean to me.

2024-02-12 15:26 UTC, ahouseholder commented
@j--- since you had originally requested changes, I think you have to re-review and approve this to clear the way to merge.

2024-02-13 17:45 UTC, j--- approved these changes
Thanks for sorting this all out!

2024-02-13 18:32 UTC, merged