Related to item #79
CERTCC/SSVC pull request #90
Opened 2020-12-10 19:14 UTC by laurie-tyz

Some substitution of patch or fix for remediation or remediated.

one deletion in 047: deleted "applier".

2020-12-10 19:58 UTC, j--- requested changes
I think we should try to get all the relevant instances of "patch" with this issue if it's part of 79. So in 040_treesForVulMgmt.md, the headings "supplying patches" etc. and the language in those sections needs to be updated to reflect we are talking about mitigations in general with SSVC. Currently those sections imply SSVC is only about patches.

2020-12-11 15:50 UTC, laurie-tyz commented
I don't believe these changes will fully close out the "patch" or "fix" issue.  I wanted to start slowly with *some* changes that appear obvious.  So a partial solution.  The rest of the plan was to start from the beginning (again) and identify those patch/fix instances that should really be mitigation/remediation.

Your call on how you want it done.

2020-12-11 16:03 UTC, j--- approved these changes
OK, if that's the plan then this looks good to me.

2020-12-14 19:16 UTC, j--- commented on doc/version_1/047_treesForVulMgmt_4.md
> +The SSVC version 1 deployer tree had 225 rows when we wrote it out in long text form.
I had this in strikeout (~tilde~) on purpose to make it clear that it was called something else in v1, so if a reader goes to look at the v1 doc they know it was called applier then, though we have changed it to deployer now. So I think this should stay. Sorry, I didn't catch this earlier.

2020-12-14 19:19 UTC, merged